### ISSUE TITLE
copied requests or drafts throw errors when readout mode is changed

### ISSUE THREAD

**Issue by emannenicholas** [LCOGT/observation-portal-frontend#111]
When an existing 1m0 Sinistro request is copied or taken from drafts, and the readout mode is changed, an error is thrown (see picture).  This error can be circumvented by changing the instrument type, and then changing it back, but it would be nice to not have to do that.

![copied_drafts_bug](https://github.com/user-attachments/assets/c478a2c8-0457-4b8d-86d6-8493bb8919a3)

**Comment by jnation3406** [comment]
So this looks like its due to when we submit a request, it gets extra params for the binning added (for site-software) based on its readout mode. I think the way to tackle this would be to remove the bin_x/bin_y from extra_params if the readout mode is changed, or just remove those values completely on copying a request, since they will get auto populated on submission if they are needed.
